# Generated by Django 4.1.7 on 2023-03-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_stat',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
