# Generated by Django 4.1.7 on 2023-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bids_id_bids_bidder_name_bids_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidder_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bids',
            name='title',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
