# Generated by Django 4.1.7 on 2023-07-19 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_id_alter_listing_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='bid',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='listing',
        ),
        migrations.AddField(
            model_name='bids',
            name='list_title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.ManyToManyField(blank=True, to='auctions.bids')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
