# Generated by Django 4.1.7 on 2023-07-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bid_bids_value_remove_bids_listing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserAssoc',
        ),
    ]
