# Generated by Django 4.1.7 on 2023-07-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_bidder_name_alter_bids_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidder_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bids',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
