# Generated by Django 4.1.7 on 2023-07-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bids_bidder_name_alter_bids_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.TextField(null=True),
        ),
    ]
