# Generated by Django 4.1.7 on 2023-07-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bids_bid_rename_userinfo_userassoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder_name',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='list_title',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_counter',
            field=models.IntegerField(default=1),
        ),
    ]
