# Generated by Django 4.1.7 on 2023-07-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_listing_comment_list_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_winner',
            field=models.CharField(default='', max_length=64),
        ),
    ]
