# Generated by Django 4.1.7 on 2023-07-17 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='list_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='list',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
