# Generated by Django 4.1.7 on 2023-07-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comments_creator_alter_bids_bidder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bid_counter',
        ),
        migrations.AddField(
            model_name='comments',
            name='list_title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='bidder_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
